# Importing Libraries

In [1]:
! pip install ucimlrepo

Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.12/dist-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2025.8.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

In [2]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
heart_disease = fetch_ucirepo(id=45)

# data (as pandas dataframes)
X = heart_disease.data.features
y = heart_disease.data.targets.squeeze()

# metadata
print(heart_disease.metadata)

# variable information
print(heart_disease.variables)

{'uci_id': 45, 'name': 'Heart Disease', 'repository_url': 'https://archive.ics.uci.edu/dataset/45/heart+disease', 'data_url': 'https://archive.ics.uci.edu/static/public/45/data.csv', 'abstract': '4 databases: Cleveland, Hungary, Switzerland, and the VA Long Beach', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 303, 'num_features': 13, 'feature_types': ['Categorical', 'Integer', 'Real'], 'demographics': ['Age', 'Sex'], 'target_col': ['num'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1989, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C52P4X', 'creators': ['Andras Janosi', 'William Steinbrunn', 'Matthias Pfisterer', 'Robert Detrano'], 'intro_paper': {'ID': 231, 'type': 'NATIVE', 'title': 'International application of a new probability algorithm for the diagnosis of coronary artery disease.', 'authors': 'R. Detrano, A. Jánosi, W. Steinbrunn, M. Pfisterer, J. Schmid, S. Sandhu, K. Guppy, S. Lee, V. Froelicher', 'venue': 'American Journal of Cardiology', 'year': 1989, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/a7d714f8f87bfc41351eb5ae1e5472f0ebbe0574', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': '2756873', 'pmcid': None}, 'additional_info': {'summary': 'This database contains 76 attributes, but all published experiments refer to using a subset of 14 of them.  In particular, the Cleveland database is the only one that has been used by ML researchers to date.  The "goal" field refers to the presence of heart disease in the patient.  It is integer valued from 0 (no presence) to 4. Experiments with the Cleveland database have concentrated on simply attempting to distinguish presence (values 1,2,3,4) from absence (value 0).  \n   \nThe names and social security numbers of the patients were recently removed from the database, replaced with dummy values.\n\nOne file has been "processed", that one containing the Cleveland database.  All four unprocessed files also exist in this directory.\n\nTo see Test Costs (donated by Peter Turney), please see the folder "Costs" ', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Only 14 attributes used:\r\n      1. #3  (age)       \r\n      2. #4  (sex)       \r\n      3. #9  (cp)        \r\n      4. #10 (trestbps)  \r\n      5. #12 (chol)      \r\n      6. #16 (fbs)       \r\n      7. #19 (restecg)   \r\n      8. #32 (thalach)   \r\n      9. #38 (exang)     \r\n      10. #40 (oldpeak)   \r\n      11. #41 (slope)     \r\n      12. #44 (ca)        \r\n      13. #51 (thal)      \r\n      14. #58 (num)       (the predicted attribute)\r\n\r\nComplete attribute documentation:\r\n      1 id: patient identification number\r\n      2 ccf: social security number (I replaced this with a dummy value of 0)\r\n      3 age: age in years\r\n      4 sex: sex (1 = male; 0 = female)\r\n      5 painloc: chest pain location (1 = substernal; 0 = otherwise)\r\n      6 painexer (1 = provoked by exertion; 0 = otherwise)\r\n      7 relrest (1 = relieved after rest; 0 = otherwise)\r\n      8 pncaden (sum of 5, 6, and 7)\r\n      9 cp: chest pain type\r\n        -- Value 1: typical angina\r\n        -- Value 2: atypical angina\r\n        -- Value 3: non-anginal pain\r\n        -- Value 4: asymptomatic\r\n     10 trestbps: resting blood pressure (in mm Hg on admission to the hospital)\r\n     11 htn\r\n     12 chol: serum cholestoral in mg/dl\r\n     13 smoke: I believe this is 1 = yes; 0 = no (is or is not a smoker)\r\n     14 cigs (cigarettes per day)\r\n     15 years (number of years as a smoker)\r\n     16 fbs: (fasting blood sugar > 120 mg/dl)  (1 = true; 0 = false)\r\n     17 dm (1 = history of diabetes; 0 = no such history)\r\n     18 famhist: family history of coronary artery disease (1 = yes; 0 = no)\r\n     19 restecg: resting electrocardiographic results\r\n        -- Value 0: normal\r\n        -- Value 1: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV)\r\n        -- Value 2: showing probable or definite left ventricular hypertrophy by Estes\' criteria\r\n     20 ekgmo (month of exercise ECG reading)\r\n     21 ekgday(day of exercise ECG reading)\r\n     22 ekgyr (year of exercise ECG reading)\r\n     23 dig (digitalis used furing exercise ECG: 1 = yes; 0 = no)\r\n     24 prop (Beta blocker used during exercise ECG: 1 = yes; 0 = no)\r\n     25 nitr (nitrates used during exercise ECG: 1 = yes; 0 = no)\r\n     26 pro (calcium channel blocker used during exercise ECG: 1 = yes; 0 = no)\r\n     27 diuretic (diuretic used used during exercise ECG: 1 = yes; 0 = no)\r\n     28 proto: exercise protocol\r\n          1 = Bruce     \r\n          2 = Kottus\r\n          3 = McHenry\r\n          4 = fast Balke\r\n          5 = Balke\r\n          6 = Noughton \r\n          7 = bike 150 kpa min/min  (Not sure if "kpa min/min" is what was written!)\r\n          8 = bike 125 kpa min/min  \r\n          9 = bike 100 kpa min/min\r\n         10 = bike 75 kpa min/min\r\n         11 = bike 50 kpa min/min\r\n         12 = arm ergometer\r\n     29 thaldur: duration of exercise test in minutes\r\n     30 thaltime: time when ST measure depression was noted\r\n     31 met: mets achieved\r\n     32 thalach: maximum heart rate achieved\r\n     33 thalrest: resting heart rate\r\n     34 tpeakbps: peak exercise blood pressure (first of 2 parts)\r\n     35 tpeakbpd: peak exercise blood pressure (second of 2 parts)\r\n     36 dummy\r\n     37 trestbpd: resting blood pressure\r\n     38 exang: exercise induced angina (1 = yes; 0 = no)\r\n     39 xhypo: (1 = yes; 0 = no)\r\n     40 oldpeak = ST depression induced by exercise relative to rest\r\n     41 slope: the slope of the peak exercise ST segment\r\n        -- Value 1: upsloping\r\n        -- Value 2: flat\r\n        -- Value 3: downsloping\r\n     42 rldv5: height at rest\r\n     43 rldv5e: height at peak exercise\r\n     44 ca: number of major vessels (0-3) colored by flourosopy\r\n     45 restckm: irrelevant\r\n     46 exerckm: irrelevant\r\n     47 restef: rest raidonuclid (sp?) ejection fraction\r\n     48 restwm: rest wall (sp?) motion abnormality\r\n        0 = none\r\n        1 = mild or moderate\r\n        2 = moderate or severe\r\n        3 = akinesis or dyskmem (sp?)\r\n     49 exeref: exercise radinalid (sp?) ejection fraction\r\n     50 exerwm: exercise wall (sp?) motion \r\n     51 thal: 3 = normal; 6 = fixed defect; 7 = reversable defect\r\n     52 thalsev: not used\r\n     53 thalpul: not used\r\n     54 earlobe: not used\r\n     55 cmo: month of cardiac cath (sp?)  (perhaps "call")\r\n     56 cday: day of cardiac cath (sp?)\r\n     57 cyr: year of cardiac cath (sp?)\r\n     58 num: diagnosis of heart disease (angiographic disease status)\r\n        -- Value 0: < 50% diameter narrowing\r\n        -- Value 1: > 50% diameter narrowing\r\n        (in any major vessel: attributes 59 through 68 are vessels)\r\n     59 lmt\r\n     60 ladprox\r\n     61 laddist\r\n     62 diag\r\n     63 cxmain\r\n     64 ramus\r\n     65 om1\r\n     66 om2\r\n     67 rcaprox\r\n     68 rcadist\r\n     69 lvx1: not used\r\n     70 lvx2: not used\r\n     71 lvx3: not used\r\n     72 lvx4: not used\r\n     73 lvf: not used\r\n     74 cathef: not used\r\n     75 junk: not used\r\n     76 name: last name of patient  (I replaced this with the dummy string "name")', 'citation': None}}
        name     role         type demographic  \
0        age  Feature      Integer         Age
1        sex  Feature  Categorical         Sex
2         cp  Feature  Categorical        None
3   trestbps  Feature      Integer        None
4       chol  Feature      Integer        None
5        fbs  Feature  Categorical        None
6    restecg  Feature  Categorical        None
7    thalach  Feature      Integer        None
8      exang  Feature  Categorical        None
9    oldpeak  Feature      Integer        None
10     slope  Feature  Categorical        None
11        ca  Feature      Integer        None
12      thal  Feature  Categorical        None
13       num   Target      Integer        None

                                          description  units missing_values
0                                                None  years             no
1                                                None   None             no
2                                                None   None             no
3   resting blood pressure (on admission to the ho...  mm Hg             no
4                                   serum cholestoral  mg/dl             no
5                     fasting blood sugar > 120 mg/dl   None             no
6                                                None   None             no
7                         maximum heart rate achieved   None             no
8                             exercise induced angina   None             no
9   ST depression induced by exercise relative to ...   None             no
10                                               None   None             no
11  number of major vessels (0-3) colored by flour...   None            yes
12                                               None   None            yes
13                         diagnosis of heart disease   None             no

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler ,OneHotEncoder, OrdinalEncoder

import joblib

# Loading Dataset

In [4]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        299 non-null    float64
 12  thal      301 non-null    float64
dtypes: float64(3), int64(10)
memory usage: 30.9 KB

In [5]:
X.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          4
thal        2
dtype: int64

In [6]:
X.duplicated().sum()

np.int64(0)

In [7]:
# Get summary statistics for categorical columns
X.describe().T

          count        mean        std    min    25%    50%    75%    max
age       303.0   54.438944   9.038662   29.0   48.0   56.0   61.0   77.0
sex       303.0    0.679868   0.467299    0.0    0.0    1.0    1.0    1.0
cp        303.0    3.158416   0.960126    1.0    3.0    3.0    4.0    4.0
trestbps  303.0  131.689769  17.599748   94.0  120.0  130.0  140.0  200.0
chol      303.0  246.693069  51.776918  126.0  211.0  241.0  275.0  564.0
fbs       303.0    0.148515   0.356198    0.0    0.0    0.0    0.0    1.0
restecg   303.0    0.990099   0.994971    0.0    0.0    1.0    2.0    2.0
thalach   303.0  149.607261  22.875003   71.0  133.5  153.0  166.0  202.0
exang     303.0    0.326733   0.469794    0.0    0.0    0.0    1.0    1.0
oldpeak   303.0    1.039604   1.161075    0.0    0.0    0.8    1.6    6.2
slope     303.0    1.600660   0.616226    1.0    1.0    2.0    2.0    3.0
ca        299.0    0.672241   0.937438    0.0    0.0    0.0    1.0    3.0
thal      301.0    4.734219   1.939706    3.0    3.0    3.0    7.0    7.0

In [8]:
for col in X:
    print(f"\nColumn: {col}")
    print("**"*20)
    print(X[col].value_counts())
    print("--"*20, '\n')

Column: age
****************************************
age
58    19
57    17
54    16
59    14
52    13
51    12
60    12
62    11
56    11
44    11
41    10
64    10
63     9
67     9
53     8
61     8
43     8
45     8
55     8
65     8
42     8
46     7
66     7
48     7
50     7
49     5
47     5
70     4
39     4
68     4
35     4
40     3
69     3
71     3
37     2
34     2
38     2
29     1
77     1
74     1
76     1
Name: count, dtype: int64
----------------------------------------


Column: sex
****************************************
sex
1    206
0     97
Name: count, dtype: int64
----------------------------------------


Column: cp
****************************************
cp
4    144
3     86
2     50
1     23
Name: count, dtype: int64
----------------------------------------


Column: trestbps
****************************************
trestbps
120    37
130    36
140    32
110    19
150    17
128    12
138    12
125    11
160    11
112     9
132     8
118     7
124     6
135     6
108     6
134     5
145     5
152     5
170     4
100     4
122     4
105     3
115     3
126     3
142     3
180     3
136     3
178     2
144     2
94      2
148     2
146     2
102     2
117     1
172     1
101     1
200     1
104     1
155     1
165     1
174     1
158     1
129     1
192     1
123     1
106     1
156     1
154     1
114     1
164     1
Name: count, dtype: int64
----------------------------------------


Column: chol
****************************************
chol
204    6
234    6
197    6
254    5
269    5
      ..
187    1
157    1
176    1
241    1
131    1
Name: count, Length: 152, dtype: int64
----------------------------------------


Column: fbs
****************************************
fbs
0    258
1     45
Name: count, dtype: int64
----------------------------------------


Column: restecg
****************************************
restecg
0    151
2    148
1      4
Name: count, dtype: int64
----------------------------------------


Column: thalach
****************************************
thalach
162    11
163     9
160     9
152     8
172     7
       ..
117     1
71      1
118     1
134     1
90      1
Name: count, Length: 91, dtype: int64
----------------------------------------


Column: exang
****************************************
exang
0    204
1     99
Name: count, dtype: int64
----------------------------------------


Column: oldpeak
****************************************
oldpeak
0.0    99
1.2    17
0.6    14
1.0    14
0.8    13
1.4    13
0.2    12
1.6    11
1.8    10
0.4     9
2.0     9
0.1     7
2.6     6
2.8     6
3.0     5
1.5     5
1.9     5
0.5     5
3.6     4
2.2     4
0.9     3
0.3     3
4.0     3
2.4     3
3.4     3
2.3     2
1.1     2
3.2     2
2.5     2
4.2     2
3.5     1
3.1     1
1.3     1
2.9     1
5.6     1
6.2     1
2.1     1
3.8     1
0.7     1
4.4     1
Name: count, dtype: int64
----------------------------------------


Column: slope
****************************************
slope
1    142
2    140
3     21
Name: count, dtype: int64
----------------------------------------


Column: ca
****************************************
ca
0.0    176
1.0     65
2.0     38
3.0     20
Name: count, dtype: int64
----------------------------------------


Column: thal
****************************************
thal
3.0    166
7.0    117
6.0     18
Name: count, dtype: int64
----------------------------------------

In [9]:
X.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca          float64
thal        float64
dtype: object

In [10]:
# Specify categorical columns (numeric but categorical)
categorical_cols = [
    "sex",        # 0=female, 1=male
    "cp",         # chest pain type (0-3)
    "fbs",        # fasting blood sugar (0/1)
    "restecg",    # resting ECG (0-2)
    "exang",      # exercise induced angina (0/1)
    "slope",      # slope of ST segment (0-2)
    "ca",         # major vessels (0-3)
    "thal"        # thalassemia (3,6,7)
]
numerical_cols = [col for col in X.columns if col not in categorical_cols]

In [11]:
# Imputing for future missing input data
num_imputer = SimpleImputer(strategy='mean')
X[numerical_cols] = num_imputer.fit_transform(X[numerical_cols])
cat_imputer = SimpleImputer(strategy='most_frequent')
X[categorical_cols] = cat_imputer.fit_transform(X[categorical_cols])

In [12]:
# One-hot encoding for nominal categorical data
ordinal_cols = ["slope", "restecg", "ca"]      # has order
nominal_cols = ["sex", "cp", "fbs", "exang", "thal"]   # no order
# Ordinal encoding for ordinal categorical data
ord_encoder = OrdinalEncoder()
X[ordinal_cols] = ord_encoder.fit_transform(X[ordinal_cols])

# One-hot encoding for nominal categorical data
ohe = OneHotEncoder(sparse_output=False, drop="first")
nominal_encoded = ohe.fit_transform(X[nominal_cols])
nominal_encoded_df = pd.DataFrame(
    nominal_encoded,
    columns=ohe.get_feature_names_out(nominal_cols),
    index=X.index
)

# Drop nominal & concat encoded
X = X.drop(columns=nominal_cols)
X = pd.concat([X, nominal_encoded_df], axis=1)

In [13]:
X.dtypes

age          float64
trestbps     float64
chol         float64
restecg      float64
thalach      float64
oldpeak      float64
slope        float64
ca           float64
sex_1.0      float64
cp_2.0       float64
cp_3.0       float64
cp_4.0       float64
fbs_1.0      float64
exang_1.0    float64
thal_6.0     float64
thal_7.0     float64
dtype: object

In [14]:
# Scale numerical features
scaler = StandardScaler()
X[numerical_cols] = scaler.fit_transform(X[numerical_cols])

In [15]:
X.head()

,age,trestbps,chol,restecg,thalach,oldpeak,slope,ca,sex_1.0,cp_2.0,cp_3.0,cp_4.0,fbs_1.0,exang_1.0,thal_6.0,thal_7.0
0,0.948726,0.757525,-0.264900,2.0,0.017197,1.087338,2.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,1.392002,1.611220,0.760415,2.0,-1.821905,0.397182,1.0,3.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,1.392002,-0.665300,-0.342283,2.0,-0.902354,1.346147,1.0,2.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
3,-1.932564,-0.096170,0.063974,0.0,1.637359,2.122573,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,-1.489288,-0.096170,-0.825922,2.0,0.980537,0.310912,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
# change target 2 binary class
# Original target
print("Original target distribution (5 classes):")
print(y.value_counts().sort_index())

Original target distribution (5 classes):
num
0    164
1     55
2     36
3     35
4     13
Name: count, dtype: int64

In [17]:
# Convert to binary: 0 = no disease, 1 = disease (classes 1-4)
target_binary = (y > 0).astype(int)
# Verify new distribution
print("\nBinary target distribution:")
print(pd.Series(target_binary).value_counts().sort_index())
print(f"Binary classes: {np.unique(target_binary)}")

Binary target distribution:
num
0    164
1    139
Name: count, dtype: int64
Binary classes: [0 1]

In [18]:
target_binary.to_csv('/content/drive/MyDrive/datasets/Heart_Disease_Project/target_binary.csv',
                     index=False, header=["target"])

In [19]:
# Save preprocessing objects
joblib.dump(num_imputer, '/content/drive/MyDrive/datasets/Heart_Disease_Project/num_imputer.pkl')
joblib.dump(cat_imputer, '/content/drive/MyDrive/datasets/Heart_Disease_Project/cat_imputer.pkl')
joblib.dump(scaler, '/content/drive/MyDrive/datasets/Heart_Disease_Project/scaler.pkl')
joblib.dump(ord_encoder, '/content/drive/MyDrive/datasets/Heart_Disease_Project/ordinal_encoder.pkl')
joblib.dump(ohe, '/content/drive/MyDrive/datasets/Heart_Disease_Project/onehot_encoder.pkl')
joblib.dump(list(X.columns), "/content/drive/MyDrive/datasets/Heart_Disease_Project/feature_columns.pkl")


print("Data preprocessing completed and saved.")

Data preprocessing completed and saved.